### ISSUE TITLE
Specifying HEADERS for non pixel devices

### ISSUE THREAD

**Issue by nitanmarcel** [yanivagman/BPFroid#15]
Make sure to build the kernel in the same directory and run make defconfig and make prepare without the O=.. switch

**Old text:**

What path should I use when I'm building for non pixel devices?

The contents of my kernel sources look like this:

```
AndroidKernel.mk  Documentation  Makefile	      build.config.common		certs		 firmware		init		  mm	   security  verity_dev_keys.x509
Androidbp	 Kbuild	README		      build.config.cuttlefish.aarch64	config.sh	 fs			ipc		  net	   sound     virt
AnyKernel3	 Kconfig	arch		      build.config.cuttlefish.x86_64	crypto		 gen_headers_arm.bp	kernel		  out	   techpack
COPYING		 KernelSU	block		      build.config.x86_64		disable_dbgfs.sh  gen_headers_arm64.bp	kernel_headers.py  samples  tools
CREDITS		 MAINTAINERS	build.config.aarch64  build.sh				drivers		 include		lib		  scripts  usr
```

If I use the kernel directory as headers I run into

`/headers//include/linux/kconfig.h:5:10: fatal error: 'generated/autoconf.h' file not found`

If I use out or include as headers I run into

`[..]/include/include/linux/kconfig.h' file not found`

**Comment by nitanmarcel** [comment]
I think I have fixed it?

I had to do `make headers_install INSTALL_HDR_PATH=$(pwd)/headers O=out;`

Then I noticed that not everything was created correctly so I copied the missing headers

**Comment by yanivagman** [comment]
You can see in the makefile to where I pointed HEADERS both for the emulator and pixel3a: https://github.com/yanivagman/BPFroid/blob/main/Makefile#L16

In Tracee (the project BPFroid is based on) we actually don't use kernel headers anymore since we moved to use CO-RE bpf object. If I had the time to update this project (unfortunately I don't) I would convert the bpf code to be CO-RE ready and generate BTFs for different Android devices - this will remove the requirement to include kernel headers and actually one (precompiled) binary would fit any Android device for which we generated a BTF

**Comment by nitanmarcel** [comment]
> You can see in the makefile to where I pointed HEADERS both for the emulator and pixel3a: https://github.com/yanivagman/BPFroid/blob/main/Makefile#L16
> 
> In Tracee (the project BPFroid is based on) we actually don't use kernel headers anymore since we moved to use CO-RE bpf object. If I had the time to update this project (unfortunately I don't) I would convert the bpf code to be CO-RE ready and generate BTFs for different Android devices - this will remove the requirement to include kernel headers and actually one (precompiled) binary would fit any Android device for which we generated a BTF

Right. Well given by https://github.com/yanivagman/BPFroid/blob/dc786d1f4bedff775c22fd2cb7db71776df8212c/Makefile#L17

I suppose I need to make headers_install while adding the missing headers as mentioned by https://stackoverflow.com/a/31867036/9782042

The first one seems to be the kernel directory which fails for me as specified in the first error

**Comment by nitanmarcel** [comment]
Ah, actually for some reason specifying the kernel location worked, no idea why

**Comment by nitanmarcel** [comment]
It was fixed by making the defconfig and making make prepare
