### ISSUE TITLE
Could you open source the boot image mentioned in the article?

### ISSUE THREAD

**Issue by csyjyy** [yanivagman/BPFroid#6]
First of all, thank you very much for open sourcing this project.
After I compiled the entire project, I found that libbpf could not be loaded when the pixel 3a xl was running, and the error message was as follows:
libbpf: load bpf program failed: Permission denied
libbpf: -- BEGIN DUMP LOG ---
.........
R1 type=map_value expected=fp

libbpf: -- END LOG --
libbpf: failed to load program 'tracepoint__raw_syscalls__sys_enter'
libbpf: failed to load object '/data/local/tmp/dist/tracee.bpf..o'

Then, I read your article carefully and found that uprobes support needs to be added. I found a lot of information but failed to add it on the pixel 3a xl phone, so can you open source the modified boot image image mentioned in the article?
Looking forward to your reply!

**Comment by yanivagman** [comment]
Hello @csyjyy,

Thanks!
I was actually convinced this was already part of the repo, not sure why I didn't include it previously.
I just commited the "pixel 3a" directory (https://github.com/yanivagman/BPFroid/tree/main/pixel%203a) which includes all the images and patches I used, both for android-10 and android-11.
Hope this helps.

**Comment by csyjyy** [comment]
@yanivagman thanks!
