### ISSUE TITLE
The compiled file runs with an error!

### ISSUE THREAD

**Issue by csyjyy** [yanivagman/BPFroid#7]
hello @yanivagman 
I compiled bpfroid according to your readme, the environment is Ubuntu22.04, the specific command is as follows:
1.docker run -it --rm --privileged multiarch/qemu-user-static --credential yes --persistent yes
2. Use the Dockerfile in the build directory to generate a compilation environment
3. docker run -it --rm -v /path/to/BPFroid:/tracee -v /path/to/android-kernel:/headers bpfroid_builder
4. In the container bpfroid_builder, enter the tracee directory, modify the header field in the Makefile file, that is header=/headers, and then make
5. Finally, the dist directory is generated under the directory, and the files contained in it are as follows:
libbpf  tracee  tracee.bpf  tracee.bpf..o  tracee.bpf.tar.gz
6. I push the dist directory to /data/local/tmp,then run the tracee binary.
the following error was reported：

bonito:/data/local/tmp/dist # ls
hooks.json  libbpf  tracee  tracee.bpf  tracee.bpf..o  tracee.bpf.tar.gz
bonito:/data/local/tmp/dist # ./tracee
libbpf: load bpf program failed: Invalid argument
libbpf: -- BEGIN DUMP LOG ---
libbpf: 
back-edge from insn 3244 to 3228

libbpf: -- END LOG --
libbpf: failed to load program 'trace_ret_vfs_write_tail'
libbpf: failed to load object '/data/local/tmp/dist/tracee.bpf..o'

I am new to android ebpf, please guide me in detail where is the problem of compiling, thank you very much!

**Comment by yanivagman** [comment]
Can you please try to modify the `do_vfs_write_writev_tail` function in tracee.bpf.c file?
You can simply `return 0` at the start of this function to ignore its content. This will not affect the main functionality of BPFroid

**Comment by csyjyy** [comment]
I have modified it, but still report the same error.
static __always_inline int do_vfs_write_writev_tail(struct pt_regs *ctx, u32 event_id)
{
    return 0;
}
the same error info:
bonito:/data/local/tmp/dist # ./tracee                                                     
libbpf: load bpf program failed: Invalid argument
libbpf: -- BEGIN DUMP LOG ---
libbpf: 
back-edge from insn 3244 to 3228

libbpf: -- END LOG --
libbpf: failed to load program 'trace_ret_vfs_write_tail'
libbpf: failed to load object '/data/local/tmp/dist/tracee.bpf..o'

**Comment by yanivagman** [comment]
It seems that you still load the old bpf object.
Verify that you compiled the new code using the ARM64 emulator and moved it to the target device correctly

**Comment by csyjyy** [comment]
Thank you very much, the problem has been solved.

**Comment by csyjyy** [comment]
There are too many log information, should bpfroid be able to track specific applications? What parameters need to be specified at runtime?

**Comment by yanivagman** [comment]
Sure. There are many filters available in bpfroid which are inherited from tracee. These include pid, uid, command name, and more filters. You can run bpfroid using `--trace help` to see more available filters.
Other than those filters I also added a filter which is specific to android named `package`. You can use it to filter for specific application packages using `--trace package=some_package`
